# Generated by Django 2.2 on 2020-08-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('search_text', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'search_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=200)),
                ('created', models.CharField(max_length=200)),
                ('id_tw', models.IntegerField()),
            ],
        ),
    ]
